# Generated by Django 2.2 on 2019-04-04 20:41

import CRM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='credit_card',
            field=models.CharField(auto_created=True, default=CRM.models.generateCreditCardNumber, max_length=16, unique=True),
        ),
    ]
