# Generated by Django 2.2 on 2019-04-04 21:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_auto_20190404_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 4, 21, 17, 59, 299911, tzinfo=utc)),
        ),
    ]
