# Generated by Django 2.2 on 2019-04-04 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_account_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
