# Generated by Django 2.2 on 2019-04-05 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0006_auto_20190404_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='CIN',
            new_name='cin',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Nationality',
            new_name='nationality',
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='opening_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
