# Generated by Django 2.2 on 2019-04-05 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_auto_20190405_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 4, 11, 7, 32, 794671, tzinfo=utc)),
        ),
    ]
