# Generated by Django 2.2 on 2019-04-05 21:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_auto_20190405_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 4, 21, 25, 18, 858871, tzinfo=utc)),
        ),
    ]
