# Generated by Django 2.2 on 2019-04-06 10:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0014_auto_20190406_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 5, 10, 8, 34, 245743, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='payment_account', to='CRM.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='receiver_account', to='CRM.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sender_account', to='CRM.Account'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='withdrawal_account', to='CRM.Account'),
        ),
    ]
