# Generated by Django 2.2 on 2019-04-07 05:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0015_auto_20190406_1008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Deposit',
        ),
        migrations.AlterField(
            model_name='account',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 6, 5, 23, 58, 664584, tzinfo=utc)),
        ),
    ]
