# Generated by Django 2.2 on 2019-04-09 21:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0017_auto_20190407_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birthDate',
            new_name='birth_date',
        ),
        migrations.AlterField(
            model_name='account',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 8, 21, 33, 24, 545451, tzinfo=utc)),
        ),
    ]
