# Generated by Django 2.2 on 2019-04-25 20:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0018_auto_20190409_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 24, 20, 0, 24, 686868, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
